### PR TITLE
Fix csm-status

### PR DESCRIPTION
**Pull request by abhi16394**
# Description
Csm-status was not updating when driver alone was installed 
Fixed it by realigning the code to work when driver is also installed

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1130|

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Driver installed through csm-operator and csm-status succeded
image

### CODE REVIEW

**Review by gallacher — APPROVED** [review]
LGTM

**Comment by cbartoszDell** [comment]
I don't see any unit tests modified/added.

**Comment by abhi16394** [comment]
> I don't see any unit tests modified/added.

i have not added any new feature 
so no new unit-tests to be added

**Comment by cbartoszDell** [comment]
Without unit test we can't be sure we will not introduce regression/change behavior of this function in the future. There are multiple paths in this function, we should have unit tests covering every path if possible.

**Comment by abhi16394** [comment]
> Without unit test we can't be sure we will not introduce regression/change behavior of this function in the future. There are multiple paths in this function, we should have unit tests covering every path if possible.

We have covered this functionality before as unit-tests are passing
All the functions or conditions will be called in this case

**Comment by cbartoszDell** [comment]
There is no status_test.go file in the codebase. Where can I find unit tests that cover those changes?

**Comment by abhi16394** [comment]
> There is no status_test.go file in the codebase. Where can I find unit tests that cover those changes?

It is called from csm_controller_test.go
Yeah we never had status_test.go file since the code inside status.go file would be called from csm_controller.go file

**Review by bharathsreekanth — APPROVED** [review]

**Review by gallacher — CHANGES_REQUESTED** [review]
Your branch needs to be created off release-v1.4.2

**Comment by cbartoszDell** [comment]
There are errors in logs for unit tests step.

**Comment by cbartoszDell** [comment]
LGTM

**Comment by abhi16394** [comment]
raised a new PR to create a branch based of release-v1.4.2: https://github.com/dell/csm-operator/pull/454

**Pull request closed without merging**
