### PR TITLE
Application mobility (#419)

### PR DESCRIPTION
**Pull request by jooseppi-luna**
# Description
This PR adds support for installation and management of app-mobility by csm-operator for use in the Kubernetes Navigator for Apex. There are no sample files or documentation included for customer use, as this product will only be available through Navigator/Apex. This work was completed by @abhi16394, @mbasha-dell, @jooseppi-luna, @JacobGros, and @kumarkgosa but has been all squashed into a couple commits here to resolve unsigned commits.

There are three main components to this PR:
- Full support for creating app-mobility controller, velero, restic, cert-manager, and all related secrets etc., except for the license secret (that will come through Apex).
- Full unit test coverage of all added code
- Full suite of E2E tests proving the effectiveness of the solution

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
- [x] Unit tests
- [x] E2E tests

### CODE REVIEW

**Review by mbasha-dell — APPROVED** [review]
Looks good. I'm good with this being merged, just had the following question --

Is this being tracked somewhere? https://github.com/dell/csm-operator/blob/f99d6192cd7d820f6d78a28f23986623c8b61cf1/pkg/utils/status.go#L48

**Comment by jooseppi-luna** [comment]
> Looks good. I'm good with this being merged, just had the following question --
> 
> Is this being tracked somewhere?
> 
> https://github.com/dell/csm-operator/blob/f99d6192cd7d820f6d78a28f23986623c8b61cf1/pkg/utils/status.go#L48

@mbasha-dell thanks for the review! This is related to work done by @rajendraindukuri (IIRC) in an earlier PR. I believe he filed something with K8s. It's not being introduced in this PR, it's already in main.

**Review by JacobGros — DISMISSED** [review]
Assuming the E2E passes LGTM
Awesome work bringing it all together @jooseppi-luna

**Review by abhi16394 — APPROVED** [review]
LGTM 
Thanks @jooseppi-luna

**Review by mbasha-dell — APPROVED** [review]
LGTM

**Review by JacobGros — APPROVED** [review]
LGTM

**Pull request merged**
