### PR TITLE
Observability update for powerscale and powerflex

### PR DESCRIPTION
**Pull request by HarishH-DELL**
# Description
Observability update for powerscale and powerflex
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1012 |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by panigs7 — DISMISSED** [review]

**Review by panigs7 — COMMENTED** [review]
We can remove v1.4.0 of observability https://github.com/dell/csm-operator/tree/main/operatorconfig/moduleconfig/observability/v1.4.0 as we support only n-2 versions.

**Comment by HarishH-DELL** [comment]
> We can remove v1.4.0 of observability https://github.com/dell/csm-operator/tree/main/operatorconfig/moduleconfig/observability/v1.4.0 as we support only n-2 versions.

removed

**Review by chimanjain — APPROVED** [review]
LGTM

**Review by shefali-malhotra — DISMISSED** [review]
LGTM

**Review by chimanjain — APPROVED** [review]
LGTM

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Pull request merged**
