### PR TITLE
Update Authorization proxy server to expose services

### PR DESCRIPTION
**Pull request by shaynafinocchiaro**
# Description
PR to add role service and storage service addresses to the proxy server for v1.6.0 and make namespace configurable throughout manifest. 

Removes v1.3.0 related manifests to follow n-2 versioning.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/408 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Tested with dellctl volume list cmd 

```
dellctl volume list --insecure true --proxy https://authorization-ingress-nginx-controller.authorization.svc.cluster.local:30895/proxy/volumes --namespace vxflexos
NAME             VOLUME ID          SIZE       POOL     SYSTEM ID          PV NAME          PV STATUS   STORAGE CLASS   PVC NAME                NAMESPACE
k8s-bef456fe25   b5aec54500000009   8.000000   mypool   x	           k8s-bef456fe25   Bound       vxflexos-xfs    vol-create-test-9hzzf   volumeio-test-1b605639
k8s-76d1a6f499   b5aec54400000008   8.000000   mypool   x 		   k8s-76d1a6f499   Bound       vxflexos        vol-create-test-pc2mw   volumeio-test-4ec858dc
k8s-e9bab92233   b5aec54b0000000f   8.000000   mypool   x 		   k8s-e9bab92233   Bound       vxflexos-xfs    vol-create-test-dtddb   volumeio-test-1b605639
k8s-01d22c1f80   b5aec5480000000c   8.000000   mypool   x 		   k8s-01d22c1f80   Bound       vxflexos        vol-create-test-plhxg   volumeio-test-4ec858dc
k8s-2af899f72b   b5aec5470000000b   8.000000   mypool   x 		   k8s-2af899f72b   Bound       vxflexos-xfs    vol-create-test-xgw2t   volumeio-test-1b605639
k8s-977fb8f0b9   b5aec54200000005   8.000000   mypool   x 		   k8s-977fb8f0b9   Bound       vxflexos        vol-create-test-wwdhk   volumeio-test-4ec858dc
k8s-f110faf812   b5aec54a0000000e   8.000000   mypool   x 		   k8s-f110faf812   Bound       vxflexos        vol-create-test-5tqqj   volumeio-test-4ec858dc
k8s-43e74d5a20   b5aec5490000000d   8.000000   mypool   x 		   k8s-43e74d5a20   Bound       vxflexos-xfs    vol-create-test-thjm2   volumeio-test-1b605639
k8s-641d4564fc   b5aec5460000000a   8.000000   mypool   x 		   k8s-641d4564fc   Bound       vxflexos        vol-create-test-qxnn8   volumeio-test-4ec858dc
k8s-c77418cf3c   b5aec54300000007   8.000000   mypool   x 		   k8s-c77418cf3c   Bound       vxflexos-xfs    vol-create-test-mm29v   volumeio-test-1b605639
```

### CODE REVIEW

**Comment by alikdell** [comment]
Why are we changing for 1.3.0 and 1.4.0 release yamls?

**Review by IsaiasA1 — DISMISSED** [review]

**Review by sharmilarama — DISMISSED** [review]

**Comment by alikdell** [comment]
Add novus team in codeowners

**Comment by rensyct** [comment]
@shaynafinocchiaro, as per the description it is for v1.6.0. Then why are we updating the manifests for versions prior to 1.6.0?

**Comment by rensyct** [comment]
@shaynafinocchiaro please remove 1.3.0 related manifests as we support only n-2 versions of driver and modules
@tdawe and @bharathsreekanth , please share your thoughts on the same

**Comment by tdawe** [comment]
> This comment is not in the scope of this PR and can be addressed in another PR if needed @shaynafinocchiaro please remove 1.3.0 related manifests as we support only n-2 versions of driver and modules @tdawe and @bharathsreekanth , please share your thoughts on the same

Agreed, we will need a new story to remove old manifests from the operator. @bharathsreekanth can that be created and assigned to a team? Thanks

**Comment by rensyct** [comment]
> > This comment is not in the scope of this PR and can be addressed in another PR if needed @shaynafinocchiaro please remove 1.3.0 related manifests as we support only n-2 versions of driver and modules @tdawe and @bharathsreekanth , please share your thoughts on the same
> 
> Agreed, we will need a new story to remove old manifests from the operator. @bharathsreekanth can that be created and assigned to a team? Thanks

Driver teams have taken care of this when adding support for the newer version. Open PRs from PowerScale and PowerDlex have taken care of this

**Comment by prablr79** [comment]
@shaynafinocchiaro can we merge this PR ? I do see this PR is bit out of date base branch.  can you please re-base this quickly ?

**Comment by shaynafinocchiaro** [comment]
@rensyct Please help review I've removed v1.3.0 related manifests. Thank you

**Review by alikdell — APPROVED** [review]

**Review by rensyct — APPROVED** [review]

**Comment by bharathsreekanth** [comment]
> This comment is not in the scope of this PR and can be addressed in another PR if needed @shaynafinocchiaro please remove 1.3.0 related manifests as we support only n-2 versions of driver and modules @tdawe and @bharathsreekanth , please share your thoughts on the same

I think we should stick to n-2 version in CSM operators. It would make things hard to track if we deviated from that and added more versions.

**Pull request merged**
