### PR TITLE
Added support for CSI PowerScale v2.9.0

### PR DESCRIPTION
**Pull request by mdutka-dell**
# Description
Added CSI PowerScale v2.9.0 support and removed v2.6.0 config.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1012 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Installed the `csi-powerscale` driver using `csm-operator` and the installation is successful
- [x] Ran `cert-csi` with supported protocols the `cert-csi` passed with 100%

### CODE REVIEW

**Review by cbartoszDell — DISMISSED** [review]

**Comment by chimanjain** [comment]
Update sidecar versions:
```
attacher: (http://registry.k8s.io/sig-storage/csi-attacher:v4.4.2)
provisioner: (http://registry.k8s.io/sig-storage/csi-provisioner:v3.6.2)
snapshotter: (http://registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2)
resizer: (http://registry.k8s.io/sig-storage/csi-resizer:v1.9.2)
registrar: (http://registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.2)
healthmonitor: (http://registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.10.0)
```

**Comment by chimanjain** [comment]
Can you update the powerscale driver in: https://github.com/dell/csm-operator/blob/csi_powerscale_samples_2.9.0/pkg/modules/testdata/cr_powerscale_observability.yaml

**Comment by adamginna-dell** [comment]
> Can you update the powerscale driver in: https://github.com/dell/csm-operator/blob/csi_powerscale_samples_2.9.0/pkg/modules/testdata/cr_powerscale_observability.yaml

I Updated cr_powerscale_observability.yaml

**Review by HarishH-DELL — APPROVED** [review]
LGTM

**Review by chimanjain — APPROVED** [review]
LGTM

**Pull request merged**
