### PR TITLE
Added patch verb for volumesnapshot creation in CSI-PowerScale

### PR DESCRIPTION
**Pull request by chimanjain**
# Description

Add patch permission for volumesnapshots in csm-isilon-controller

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/975 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Sanity Test
 
Screenshot 2023-10-11 124918

Screenshot 2023-10-11 124900

### CODE REVIEW

**Review by nitesh3108 — APPROVED** [review]

**Review by nitesh3108 — DISMISSED** [review]

**Review by jooseppi-luna — COMMENTED** [review]
1) Were you able to replicate the customer issue before the fix and show that it wasn't happening anymore after the fix?
2) Did you at a minimum run all the PScale e2e tests against the change?

**Review by alikdell — APPROVED** [review]

**Comment by chimanjain** [comment]
> 1. Were you able to replicate the customer issue before the fix and show that it wasn't happening anymore after the fix?
> 2. Did you at a minimum run all the PScale e2e tests against the change?

Yes, I was able to replicate the issue, before the status of volumesnapshotclass was coming false and I was not able to create a pvc from it but after the modifications, the status is being shown as true and I was able to create pvc from it.

**Comment by bharathsreekanth** [comment]
@chimanjain Is there a JIRA associated with this PR (corresponding to the GH issue mentioned)?

**Review by shefali-malhotra — DISMISSED** [review]
LGTM

**Comment by jooseppi-luna** [comment]
> > 1. Were you able to replicate the customer issue before the fix and show that it wasn't happening anymore after the fix?
> > 2. Did you at a minimum run all the PScale e2e tests against the change?
> 
> Yes, I was able to replicate the issue, before the status READYTOUSE of volumesnapshotclass was coming false and I was not able to create a pvc from it but after the modifications, the status is being shown as true and I was able to create pvc from it.

Ok that's great -- and did you run the PowerScale E2E tests against the fix as well? If you need help with this feel free to reach out to me.

**Comment by chimanjain** [comment]
> > > 1. Were you able to replicate the customer issue before the fix and show that it wasn't happening anymore after the fix?
> > > 2. Did you at a minimum run all the PScale e2e tests against the change?
> > 
> > 
> > Yes, I was able to replicate the issue, before the status READYTOUSE of volumesnapshotclass was coming false and I was not able to create a pvc from it but after the modifications, the status is being shown as true and I was able to create pvc from it.
> 
> Ok that's great -- and did you run the PowerScale E2E tests against the fix as well? If you need help with this feel free to reach out to me.

Yes, they were successful.

**Review by panigs7 — APPROVED** [review]

**Review by nitesh3108 — APPROVED** [review]

**Pull request merged**
