### PR TITLE
Adding owner-reference

### PR DESCRIPTION
**Pull request by abhi16394**
# Description
Adding owner-reference support to csm-operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/255 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by rensyct — DISMISSED** [review]
@abhi16394 , as discussed in today's demo meet, please test the below scenarios and ensure that they work before this PR gets merged

1. Uninstall of operator should not impact the driver (installed using csm-operator) and the objects created by the driver. Driver pods should be up and running even when the operator is not installed. All objects created by the driver should not be impacted with the uninstall of operator
2. Driver installed by dell-csi-operator and csm-operator should coexist in the same cluster in different namespaces
3. Upgrading operator should not impact driver pods or the objects created by the driver.

**Comment by yifeijin** [comment]
Looks like rebase is needed after Michael's PR

**Comment by abhi16394** [comment]
> @abhi16394 , as discussed in today's demo meet, please test the below scenarios and ensure that they work before this PR gets merged
> 
> 1. Uninstall of operator should not impact the driver (installed using csm-operator) and the objects created by the driver. Driver pods should be up and running even when the operator is not installed. All objects created by the driver should not be impacted with the uninstall of operator
> 2. Driver installed by dell-csi-operator and csm-operator should coexist in the same cluster in different namespaces
> 3. Upgrading operator should not impact driver pods or the objects created by the driver.

I verified above scenarios. Hence closing the request .

**Comment by abhi16394** [comment]
need to rebase , so closing the PR and opening a new one

**Pull request closed without merging**
