### PR TITLE
Update GO version

### PR DESCRIPTION
**Pull request by karthikk92**
# Description
Update GO version

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/491 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/csm-operator-build/206/

### CODE REVIEW

**Review by rensyct — CHANGES_REQUESTED** [review]
Why there are changes in all the manifest files.. Please rebase your branch and revert the changes made in all manifest files

**Comment by karthikk92** [comment]
> Why there are changes in all the manifest files.. Please rebase your branch and revert the changes made in all manifest files

@rensyct  rebased and now all the changes taken care after rebase.

**Review by jooseppi-luna — DISMISSED** [review]

**Review by bharathsreekanth — DISMISSED** [review]

**Review by panigs7 — DISMISSED** [review]

**Review by rensyct — APPROVED** [review]

**Comment by rensyct** [comment]
@karthikk92 , please sign your commit

**Comment by karthikk92** [comment]
> @karthikk92 , please sign your commit

taken care

**Review by rajendraindukuri — APPROVED** [review]

**Review by panigs7 — APPROVED** [review]

**Review by rensyct — APPROVED** [review]

**Pull request merged**
