### PR TITLE
Sample update

### PR DESCRIPTION
**Pull request by mbasha-dell**
# Description
Updated sample files and name/namespace references to match new docs

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/810 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran CSI-PowerFlex installation via CSM-Operator using doc's designated names and sample files
- [x] Ran 2vols test on PowerFlex installation

### CODE REVIEW

**Review by JacobGros — DISMISSED** [review]

**Review by jooseppi-luna — APPROVED** [review]

**Review by abhi16394 — COMMENTED** [review]
could you tell @KshitijaKakde to do the same for sample files 2.7.0 as she is raising a PR for powerflex 2.7.0 or you could convey the changes to her and she can raise the PR

**Review by rensyct — CHANGES_REQUESTED** [review]
Can we change the name and namespace to _powerflex_ instead of _vxflexos_

**Comment by mbasha-dell** [comment]
> Can we change the name and namespace to _powerflex_ instead of _vxflexos_

@rensyct, we plan on making this change in a future task. This isn't in the scope of this current task.

**Comment by rensyct** [comment]
@mbasha-dell , please rebase your branch. Changes to be done in 2.7 samples for Powerflex

**Comment by mbasha-dell** [comment]
Created new PR to resolve github suggesting there was more files changed than there actually were

https://github.com/dell/csm-operator/pull/244

**Pull request closed without merging**
