### PR TITLE
Update sidecar versions

### PR DESCRIPTION
**Pull request by chimanjain**
# Description

Update sidecar versions in common places.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1012 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Pulled defined images while installing the driver.
Screenshot 2023-11-21 191727

### CODE REVIEW

**Review by HarishH-DELL — APPROVED** [review]
LGTM

**Review by adarsh-dell — CHANGES_REQUESTED** [review]
Hi @chimanjain I believe csi-sidecars are not latest one, Can you please cross check and update them.
attacher: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
provisioner: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2
resizer: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.1
healthmonitor: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.10.0


I have compiled all latest version.

**Comment by adarsh-dell** [comment]
> registry.k8s.io/sig-storage/csi-node-driver-registrar

I just discovered that the registrar was released 11 hours ago.

**Comment by adarsh-dell** [comment]
> > registry.k8s.io/sig-storage/csi-node-driver-registrar
> 
> I just discovered that the registrar was released 11 hours ago.

attacher: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
provisioner: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2
resizer: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.2
healthmonitor: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.10.0

**Comment by chimanjain** [comment]
@adarsh-dell PTAL

**Review by adarsh-dell — DISMISSED** [review]
Looks good to me, Thanks @chimanjain

**Review by panigs7 — APPROVED** [review]

**Pull request merged**
