### PR TITLE
Updated csv with apex connectivity CR

### PR DESCRIPTION
**Pull request by panigs7**
# Description
Updated  CSV.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?

### CODE REVIEW

**Review by HarishH-DELL — DISMISSED** [review]
lgtm

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Review by HarishH-DELL — APPROVED** [review]

**Comment by donatwork** [comment]
The samples use apex-connectivity-client as the namespace but we should really be using dell-connectivity-client as the default namespace. Less confusing as the documentation references Dell Connectivity Client.

**Comment by donatwork** [comment]
@panigs7 Will the ApexConnectivityClient CRD be installed automatically if Operator is installed via OperatorHub?

**Pull request closed without merging**
