### PR TITLE
Cherry-pick v1.4.3 changes into operator main branch

### PR DESCRIPTION
**Pull request by jooseppi-luna**
# Description
Cherry-picking csm-operator v1.4.3 changes into main for v1.5.0 release. Also deleting unnecessary certificate sample files for observability (this was done in v1.4.3, but as part of a commit making v1.4.3 version updates, so it could not be cherry-picked over).
# GitHub Issues
| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1091 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
I am going to run csm-operator e2e tests on this branch on Monday, please review PR but do not merge -- I will merge once tests pass. Unit tests pass with no degradation of coverage.

### CODE REVIEW

**Review by mbasha-dell — APPROVED** [review]

**Review by JacobGros — APPROVED** [review]
LGTM 👍

**Review by JacobGros — APPROVED** [review]
LGTM👍

**Review by mbasha-dell — APPROVED** [review]

**Review by JacobGros — APPROVED** [review]
Re-adding my approval

**Review by bharathsreekanth — APPROVED** [review]

**Review by JacobGros — DISMISSED** [review]
Re-adding my approval (again 😄 )

**Review by JacobGros — APPROVED** [review]
Re-adding my approval (for a third time 😃 )

**Review by bharathsreekanth — APPROVED** [review]

**Pull request merged**
