### PR TITLE
Fix for sdc deployment issue

### PR DESCRIPTION
**Pull request by suryagupta4**
# Description
This PR contains fix for sdc container failing to detect the existing installation of sdc.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1152 |
| https://github.com/dell/csm/issues/1164 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] make controller-unit-test
image

- [x] make driver-unit-test
image

- [x] make module-unit-test
image

- [x] sdc init container detected the existing sdc installation
image

### CODE REVIEW

**Review by shanmydell — APPROVED** [review]

**Comment by shanmydell** [comment]
@suryagupta4 : Please fix the failing checks

**Comment by panigs7** [comment]
@suryagupta4 The controller unit tests are failing.

**Comment by suryagupta4** [comment]
@shanmydell @panigs7 
The controller unit test checks are failing in the branch `release-v1.4.3`, the changes present in that branch lowered the code coverage that caused the check to fail, we have let @jooseppi-luna know about the status and he would be working on it.

**Comment by jooseppi-luna** [comment]
@suryagupta4 actually, the controller unit tests are not failing in release-v1.4.3, only in this branch. We need to fix the coverage issue in this branch before merging.

**Review by jooseppi-luna — CHANGES_REQUESTED** [review]
controller coverage needs to be improved to >90%, I can work with you on this

**Comment by jooseppi-luna** [comment]
I first pulled the release-v1.4.3 branch locally and ran controller unit tests, got this output: 
```
PASS
coverage: 90.1% of statements in github.com/dell/csm-operator/pkg/logger, github.com/dell/csm-operator/pkg/resources/daemonset, github.com/dell/csm-operator/pkg/resources/deployment, github.com/dell/csm-operator/pkg/resources/configmap, github.com/dell/csm-operator/pkg/resources/serviceaccount, github.com/dell/csm-operator/pkg/resources/rbac, github.com/dell/csm-operator/pkg/resources/csidriver, github.com/dell/csm-operator/pkg/constants, github.com/dell/csm-operator/controllers
ok      github.com/dell/csm-operator/controllers        23.071s coverage: 90.1% of statements in github.com/dell/csm-operator/pkg/logger, github.com/dell/csm-operator/pkg/resources/daemonset, github.com/dell/csm-operator/pkg/resources/deployment, github.com/dell/csm-operator/pkg/resources/configmap, github.com/dell/csm-operator/pkg/resources/serviceaccount, github.com/dell/csm-operator/pkg/resources/rbac, github.com/dell/csm-operator/pkg/resources/csidriver, github.com/dell/csm-operator/pkg/constants, github.com/dell/csm-operator/controllers
```
I then pulled the fix-1152-sdc-deployment branch, ran the controller unit tests again, and got this:

```
PASS
coverage: 89.9% of statements in github.com/dell/csm-operator/pkg/logger, github.com/dell/csm-operator/pkg/resources/daemonset, github.com/dell/csm-operator/pkg/resources/deployment, github.com/dell/csm-operator/pkg/resources/configmap, github.com/dell/csm-operator/pkg/resources/serviceaccount, github.com/dell/csm-operator/pkg/resources/rbac, github.com/dell/csm-operator/pkg/resources/csidriver, github.com/dell/csm-operator/pkg/constants, github.com/dell/csm-operator/controllers
ok      github.com/dell/csm-operator/controllers        22.975s coverage: 89.9% of statements in github.com/dell/csm-operator/pkg/logger, github.com/dell/csm-operator/pkg/resources/daemonset, github.com/dell/csm-operator/pkg/resources/deployment, github.com/dell/csm-operator/pkg/resources/configmap, github.com/dell/csm-operator/pkg/resources/serviceaccount, github.com/dell/csm-operator/pkg/resources/rbac, github.com/dell/csm-operator/pkg/resources/csidriver, github.com/dell/csm-operator/pkg/constants, github.com/dell/csm-operator/controllers
```

So the coverage gap appears to be coming from this branch.

**Comment by suryagupta4** [comment]
@jooseppi-luna Controller UT is passing now
image

**Review by panigs7 — APPROVED** [review]

**Review by jooseppi-luna — APPROVED** [review]
lgtm thank you!

**Pull request merged**
