### PR TITLE
Add coordination.k8s.io apiGroups access for observability and update nginx image

### PR DESCRIPTION
**Pull request by chimanjain**
# Description
* Add coordination.k8s.io apiGroups access for observability
* Update `nginxinc/nginx-unprivileged` image to `1.27`
* Update `aquasecurity/trivy-action` to `0.28.0`

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1431 |
| https://github.com/dell/csm/issues/1435 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran basic sanity test(e2e) for powerflex and powerscale driver.
Screenshot 2024-10-18 124546

Screenshot 2024-10-18 142532

- [x] Installed observability module for powerscale driver and ran observability e2e test.
```
go test -v -count=1 -p 1 -race -timeout 1h ./*/metrics-test/ 2>&1 | tee metrics.txt
STORAGE_ENDPOINT env not set, using default
STORAGE_PASSWORD env not set, using default
STATELESS_AUTHORIZATION env not set
=== RUN   Test_Metrics
=== RUN   Test_Metrics/PowerScale_Cluster_Capacity_Metrics
2024/10/10 15:51:52 VolumeCount=4, WriterCount=4, ScrapeInterval=2, TestTimeout=5, CertCsiLongevityTime=10m
time="2024-10-10T15:51:52Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 4 --chainLength 4 --no-metrics --no-reports --no-cleanup --longevity %s 10m"
2024/10/10 15:51:54 PowerScale_Cluster_Capacity_Metrics success after 1 attempts
time="2024-10-10T15:51:54Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:51:54Z" level=info msg="Signal SIGKILL sent to 1726339. Waiting for process to exit..."
time="2024-10-10T15:51:54Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:51:54Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:51:54Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:52:06Z" level=info msg="Process exited without error"
=== RUN   Test_Metrics/PowerScale_Volume_Quota_Metrics
2024/10/10 15:52:06 VolumeCount=4, WriterCount=4, ScrapeInterval=2, TestTimeout=5, CertCsiLongevityTime=10m
time="2024-10-10T15:52:06Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 4 --chainLength 4 --no-metrics --no-reports --no-cleanup --longevity %s 10m"
2024/10/10 15:52:08 PowerScale_Volume_Quota_Metrics success after 1 attempts
time="2024-10-10T15:52:08Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:52:08Z" level=info msg="Signal SIGKILL sent to 1726417. Waiting for process to exit..."
time="2024-10-10T15:52:08Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:52:08Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:52:08Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:52:20Z" level=info msg="Process exited without error"
=== RUN   Test_Metrics/PowerScale_Cluster_Performance_Metrics
2024/10/10 15:52:20 VolumeCount=4, WriterCount=4, ScrapeInterval=2, TestTimeout=5, CertCsiLongevityTime=10m
time="2024-10-10T15:52:20Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 4 --chainLength 4 --no-metrics --no-reports --longevity %s 10m"
2024/10/10 15:52:22 PowerScale_Cluster_Performance_Metrics success after 1 attempts
time="2024-10-10T15:52:22Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:52:22Z" level=info msg="Signal SIGKILL sent to 1726512. Waiting for process to exit..."
time="2024-10-10T15:52:22Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:52:22Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:52:22Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:52:34Z" level=info msg="Process exited without error"
=== RUN   Test_Metrics/PowerScale_Cluster_Performance_Metrics_SmallIO
2024/10/10 15:52:34 VolumeCount=4, WriterCount=4, ScrapeInterval=2, TestTimeout=5, CertCsiLongevityTime=10m
time="2024-10-10T15:52:34Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 4 --chainLength 4 --no-metrics --no-reports --no-cleanup --longevity %s 10m"
2024/10/10 15:52:36 PowerScale_Cluster_Performance_Metrics_SmallIO success after 1 attempts
time="2024-10-10T15:52:36Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:52:36Z" level=info msg="Signal SIGKILL sent to 1726615. Waiting for process to exit..."
time="2024-10-10T15:52:36Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:52:36Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:52:36Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:52:48Z" level=info msg="Process exited without error"
=== RUN   Test_Metrics/PowerScale_Cluster_Quota_Metrics
2024/10/10 15:52:48 VolumeCount=4, WriterCount=4, ScrapeInterval=2, TestTimeout=5, CertCsiLongevityTime=10m
time="2024-10-10T15:52:48Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 4 --chainLength 4 --no-metrics --no-reports --no-cleanup --longevity %s 10m"
2024/10/10 15:52:50 PowerScale_Cluster_Quota_Metrics success after 1 attempts
time="2024-10-10T15:52:50Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:52:50Z" level=info msg="Signal SIGKILL sent to 1726702. Waiting for process to exit..."
time="2024-10-10T15:52:50Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:52:50Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:52:50Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:53:02Z" level=info msg="Process exited without error"
--- PASS: Test_Metrics (70.51s)
    --- PASS: Test_Metrics/PowerScale_Cluster_Capacity_Metrics (14.12s)
    --- PASS: Test_Metrics/PowerScale_Volume_Quota_Metrics (14.12s)
    --- PASS: Test_Metrics/PowerScale_Cluster_Performance_Metrics (14.09s)
    --- PASS: Test_Metrics/PowerScale_Cluster_Performance_Metrics_SmallIO (14.08s)
    --- PASS: Test_Metrics/PowerScale_Cluster_Quota_Metrics (14.10s)
PASS
ok      karavi-testing/karavi-metrics/metrics-test      71.629s 
```
```
go test -v -count=1 -p 1 -race -timeout 1h ./*/topology-test/ 2>&1 | tee topology.txt
=== RUN   Test_Query_Topology
2024/10/10 15:55:22 TestTimeout=4, DumpOutput=false
time="2024-10-10T15:55:22Z" level=info msg="Running: /root/cert-csi test vio --sc isilon --chainNumber 5 --chainLength 1 --no-metrics --no-reports --longevity %s 3m"
time="2024-10-10T15:55:24Z" level=info msg="Sending signal to stop cert-csi process..."
time="2024-10-10T15:55:24Z" level=info msg="Signal SIGKILL sent to 1727636. Waiting for process to exit..."
time="2024-10-10T15:55:24Z" level=info msg="Wait for cert-csi completed"
time="2024-10-10T15:55:24Z" level=info msg="Running: /root/cert-csi cleanup"
time="2024-10-10T15:55:24Z" level=info msg="Waiting for cert-csi command to finish"
time="2024-10-10T15:55:36Z" level=info msg="Process exited without error"
--- PASS: Test_Query_Topology (14.15s)
PASS
ok      karavi-testing/karavi-topology/topology-test    15.167s 
```
- [x] Verified the changes been done from nginx 1.20 to 1,27. There are no breaking changes, only addition of functionalities and bug fixes. Reference: https://nginx.org/en/CHANGES

### CODE REVIEW

**Comment by ChristianAtDell** [comment]
I see that observability E2E tests were run, according to PR description; were the logs of such test provided internally for record keeping/verification? 

Also, what is 'basic sanity test'? `tests/e2e/run-e2e-test.sh --sanity` ?

**Review by jooseppi-luna — CHANGES_REQUESTED** [review]
Please run operator e2e tests for observability and report the results in Jira (full test output for passing tests).

**Comment by chimanjain** [comment]
> Please run operator e2e tests for observability and report the results in Jira (full test output for passing tests).

Ran the csm-operator e2e test and update the result in the ticket.

**Review by rajendraindukuri — APPROVED** [review]

**Review by jooseppi-luna — APPROVED** [review]
Thanks for the e2e run!

**Pull request merged**
